import type { getAppInfoSchema, getAppListSchema } from "./interfaces/IStoreService/schema";
import type { IStoreService } from "./interfaces/IStoreService";

export type SteamInterface =
	| "IAccountCartService"
	| "IAccountPrivacyService"
	| "IAccountPrivateAppsService"
	| "IAssetSetPublishingService"
	| "IAuctionService"
	| "IAuthenticationService"
	| "IAuthenticationSupportService"
	| "IBillingService"
	| "IBroadcastService"
	| "IChatRoomService"
	| "ICheatReportingService"
	| "ICheckoutService"
	| "IClanFAQSService"
	| "IClanService"
	| "IClientCommService"
	| "IClientMetricsService"
	| "ICloudService"
	| "ICommunityService"
	| "IContentFilteringService"
	| "IContentModerationService"
	| "IContentServerConfigService"
	| "IContentServerDirectoryService"
	| "ICrashReportService"
	| "ICredentialsService"
	| "IDailyDealService"
	| "IDataPublisherService"
	| "IEconMarketService"
	| "IEconService"
	| "IEmbeddedClientService"
	| "IFamilyGroupsService"
	| "IForumsService"
	| "IFriendMessagesService"
	| "IFriendsListService"
	| "IGameCoordinator"
	| "IGameInventory"
	| "IGameNotificationsService"
	| "IGameRecordingClipService"
	| "IGameServersService"
	| "IHelpRequestLogsService"
	| "IInventoryService"
	| "ILobbyMatchmakingService"
	| "ILoyaltyRewardsService"
	| "IMarketingMessagesService"
	| "IMobileAppService"
	| "IMobileAuthService"
	| "IMobileDeviceService"
	| "IMobileNotificationService"
	| "INewsService"
	| "IOnlinePlayService"
	| "IParentalService"
	| "IPartnerAppNotesService"
	| "IPartnerDeadlineService"
	| "IPartnerDismissService"
	| "IPartnerFinancialsService"
	| "IPartnerMeetSteamService"
	| "IPartnerMembershipInviteService"
	| "IPartnerStoreBrowseService"
	| "IPhoneService"
	| "IPhysicalGoodsService"
	| "IPlayerService"
	| "IPlaytestService"
	| "IProductInfoService"
	| "IPromotionEventInvitesService"
	| "IPromotionPlanningService"
	| "IPromotionStatsService"
	| "IPublishedFileService"
	| "IPublishingService"
	| "IQuestService"
	| "IRemoteClientService"
	| "ISaleFeatureService"
	| "ISaleItemRewardsService"
	| "IShoppingCartService"
	| "ISiteLicenseService"
	| "ISteamApps"
	| "ISteamAwardsService"
	| "ISteamBitPay"
	| "ISteamBoaCompra"
	| "ISteamBroadcast"
	| "ISteamCDN"
	| "ISteamChartsService"
	| "ISteamCloudGaming"
	| "ISteamCommunity"
	| "ISteamDirectory"
	| "ISteamEconomy"
	| "ISteamEnvoy"
	| "ISteamGameServerStats"
	| "ISteamLeaderboards"
	| "ISteamLearnService"
	| "ISteamMicroTxn"
	| "ISteamMicroTxnSandbox"
	| "ISteamNews"
	| "ISteamNodwin"
	| "ISteamNotificationService"
	| "ISteamPayPalPaymentsHub"
	| "ISteamPublishedItemSearch"
	| "ISteamPublishedItemVoting"
	| "ISteamRemoteStorage"
	| "ISteamSpecialSurvey"
	| "ISteamTVService"
	| "ISteamUser"
	| "ISteamUserAuth"
	| "ISteamUserOAuth"
	| "ISteamUserStats"
	| "ISteamWebAPIUtil"
	| "ISteamWorkshop"
	| "IStoreAppSimilarityService"
	| "IStoreBrowseService"
	| "IStoreCatalogService"
	| "IStoreCurationService"
	| "IStoreMarketingService"
	| "IStorePreferencesService"
	| "IStoreQueryService"
	| "IStoreSalesService"
	| "IStoreService"
	| "IStoreTopSellersService"
	| "ITestExternalPrivilegeService"
	| "ITestService"
	| "ITrustService"
	| "ITwoFactorService"
	| "IUserAccountService"
	| "IUserGameNotesService"
	| "IUserReviewsService"
	| "IUserStoreVisitService"
	| "IVACManagementService"
	| "IVideoService"
	| "IWishlistService"
	| "IWorkshopService";

export type SteamFunctions<I extends SteamInterface> = I extends "IStoreService"
	? {
			getAppList: (
				args: typeof getAppListSchema.Encoded
			) => ReturnType<IStoreService["getAppList"]>;
			getAppListEffect: (
				args: typeof getAppListSchema.Encoded
			) => ReturnType<IStoreService["getAppListEffect"]>;

			getAppInfo: (
				args: typeof getAppInfoSchema.Encoded
			) => ReturnType<IStoreService["getAppInfo"]>;
			getAppInfoEffect: (
				args: typeof getAppInfoSchema.Encoded
			) => ReturnType<IStoreService["getAppInfoEffect"]>;
		}
	: never;
